# SPDX-License-Identifier: LGPL-2.1-or-later

# ASUS Zenbook S 16 UM5606WA: disable amdgpu PSR to avoid display freezes /
# hangs on resume (Panel Self Refresh).
[Content]
KernelCommandLine=amdgpu.dcdebugmask=0x600
