[Content]
Packages=
       file
       mimalloc
       plocate
       systemd-ukify
       distribution-gpg-keys
       zstd
       mesa-vulkan-drivers
       mt7xxx-firmware
       wofi
       gdisk
       xfsprogs
       dosfstools
       efibootmgr
       cryptsetup
       amd-gpu-firmware
       strace
       spice-vdagent
       qemu-guest-agent
       rsync
       #hyprland
       egl-utils
       pciutils
       #@kde-desktop-environment
       #weston
       tmux
       #xorg-x11-server-Xwayland
       binutils
       polkit
       tree
       btop
       iproute
       iputils
       iwd
       vim
       dbus-broker
       zsh
       less            # For nicer scrolling output for commands.
       systemd
       mkosi
       dnf
       git
       #kernel-rt
       duc
       linux-firmware
       openssh-server
       openssh-clients
       systemd-networkd-defaults
       systemd-resolved
       #systemd-boot-unsigned
       kitty
       openssl
       seatd
       #sway
       #foot
       #swayidle
       #swaylock
       #swaybg
       #wmenu
       liberation-fonts-all
       toolbox
       virt-manager
       #wayfire
       #uwsm
