# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
Packages=
        adobe-source-code-pro-fonts
        linux-firmware
        mesa
        networkmanager
        pipewire-pulse
        power-profiles-daemon
        vulkan-radeon
        file
        mimalloc
        plocate
        zstd
        gdisk
        xfsprogs
        dosfstools
        tree
        btop
        iwd
        vim
        dbus-broker
        zsh
        kitty
