# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
Packages=
        # Basic tools we should always include
        # raided from kdelinux
        # in kde-utilities
        #yakuake
        #konsole

        # does not work yet
        #linux-spudd-master

        #niri
        #noctalia
        # as soon as the 64 bit client exists
        #steam
        #steam-devices
        adobe-source-code-pro-fonts
        bat # Opinionated fancy cat
        brightnessctl
        btop
        byobu
        google-chrome-beta
        dbus-broker
        desktop-file-utils # desktop-file-validate and related useful tools
        distrobox
        dosfstools
        drm-info # for debugging KWin and other graphics issues
        duc-git
        falkon
        fastfetch # For showing off on r/unixporn
        file
        gdisk
        git-delta
        goverlay
        gum
        hunspell-en_US
        iproute2 # Basic networking tools
        iproute2 # Basic networking tools
        iw # Kernel-level wireless configuration
        iw # Kernel-level wireless configuration
        iwd
        kde-utilities
        kdiff3
        kitty
        less
        linux
        lshw # fancy hardware listing
        lsof
        mesa
        mimalloc
        nano
        neovide
        neovim
        networkmanager
        noto-fonts-cjk
        nvme-cli # NVMe SSD support tooling
        openssh
        pipewire-pulse
        plasma
        plocate
        podman
        podman-compose
        power-profiles-daemon
        ripgrep
        ripgrep
        rsync
        scx-scheds
        scx-tools
        sddm
        spice-vdagent
        strace # instrument running executables
        telegram-desktop
        tio
        tree
        tree
        unzip # the `unzip` CLI unarchiving tool
        usbutils # `lsusb` and other useful troubleshooting tools
        uwsm
        virglrenderer
        virt-manager
        vlc
        vulkan-radeon
        vulkan-virtio
        wget
        wine
        wl-clipboard
        wl-clipboard
        xdg-utils # xdg-open and other useful cross-desktop CLI tools
        xfsprogs
        zip # the `zip` CLI archiving tool
        zsh
        zsh
        zsh-autosuggestions # zsh-like suggestions
        zsh-completions
        zsh-history-substring-search # zsh-like history search
        zsh-syntax-highlighting # zsh-like syntax highlighting
        zstd
        # asus zenbook 16 S bluetooth
        linux-firmware-mediatek
        # I dont like sudo but it is everywhere, and I appreciate not being prompted at even junction
        sudo

#RemoveFiles=
#        /usr/include
#        /usr/share/man
#        /usr/share/wallpapers
#        /usr/share/doc

# breaks dep graph; use knife
#RemovePackages=
#        adwaita-icon-theme
#        adwaita-icon-theme-legacy
#        oxygen-icons
#        plasma-workspace-wallpapers
#        # cheerio baloo
#        baloo
#        adwaita-cursors
#        breeze-gtk
#        breeze-plymouth

RemovePackages=
         sddm
         sddm-kcm
         fish
         vim
         gvim
         vim-runtime
         plymouth
         breeze-plymouth
         plymouth-kcm
