# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Content]
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
Packages=
        hypridle
        hyprland
        hyprland-protocols
        hyprland-qt-support
        hyprlauncher
        hyprlock
        hyprpaper
        hyprpicker
        hyprpolkitagent
        hyprpwcenter
        hyprshot
        hyprshutdown
        hyprsunset
        quickshell
        pcmanfm-qt
        mako
        caelestia-shell
        xdg-desktop-portal-hyprland
